# Generated by Django 4.0.5 on 2022-07-04 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=800)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rating must be beetween 1 and 100'), django.core.validators.MaxValueValidator(100, message='Rating must be beetween 1 and 100')])),
            ],
        ),
    ]
