# Generated by Django 4.0.5 on 2022-07-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_store_owner_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated'), ('in_review', 'in_review')], default='in_review', max_length=12),
        ),
    ]
